import { ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";

import PageHero from "@/components/PageHero";
import ProjectCard from "@/components/ProjectCard";
import SiteLayout from "@/components/SiteLayout";
import { Button } from "@/components/ui/button";

const clientProjects = [
  {
    title: "JEE Mock Test Performance Analyst",
    description:
      "Built for a JEE coaching institute. The system takes a student's mock test results and breaks down every mistake by topic, concept, and difficulty level — so the institute can tell each student exactly where they need to improve, instead of just giving them a score.",
    tech: ["Coaching Industry", "RAG", "Performance Analytics", "LLM Pipeline"],
  },
  {
    title: "Customer Query Agent (RAG-based)",
    description:
      "An always-on agent that handles incoming customer questions for the business. It pulls answers from the business's own documents, FAQs, and past conversations — so customers get quick, accurate replies and the team stops repeating the same answers ten times a day.",
    tech: ["RAG", "Customer Support", "Agentic Workflow", "Knowledge Retrieval"],
  },
  {
    title: "Custom AI Workflows for CA Firms",
    description:
      "Automation flows built specifically for chartered accountancy firms. We map their day-to-day work — client document handling, recurring filings, internal reporting — and put AI in the spots where the team is currently doing repetitive work by hand.",
    tech: ["CA Firms", "Workflow Automation", "Document Processing", "n8n + LLM"],
  },
];

const otherWork = [
  {
    title: "AI-Powered Camera Surveillance",
    description:
      "A surveillance system that uses AI to read what is actually happening in a video feed, instead of just recording it. Built as part of our exploration into AI for physical-world businesses.",
    tags: ["Computer Vision", "Real-Time AI"],
  },
  {
    title: "NeuroVis — Brain Activity Visualisation",
    description:
      "An interactive brain visualisation tool built on top of Meta's TRIBE v2 research. It maps brain activation patterns against 14,000+ fMRI studies and predicts emotional states in real time.",
    tags: ["Meta TRIBE v2", "fMRI Decoding"],
  },
  {
    title: "Fully AI-Generated Video",
    description:
      "A short video where the face, voice, visuals, and edits were all generated by AI — no camera, no crew. Built before mainstream GenAI video tools existed. Most viewers thought it was real footage.",
    tags: ["Generative Video", "AI Content"],
  },
];

const Projects = () => {
  return (
    <SiteLayout>
      <PageHero
        eyebrow="Projects"
        title={
          <>
            <span className="block">What we have</span>
            <span className="block">
              actually <span className="accent-word">built.</span>
            </span>
          </>
        }
        description="A look at the real systems we have shipped — for paying clients, for our own R&D, and for figuring out where AI works best inside an actual business."
        metrics={[
          { label: "Active builds", value: "Coaching institutes, customer support, CA firms" },
          { label: "Stack", value: "RAG, voice agents, LLM pipelines, n8n, MCP" },
          { label: "Approach", value: "One business at a time — built around their workflow" },
        ]}
        aside={
          <div className="space-y-5">
            <p className="text-[0.68rem] font-semibold uppercase tracking-[0.24em] text-primary">How to read this page</p>
            <h2 className="text-[clamp(1.5rem,4vw,2.5rem)] font-semibold tracking-tight leading-[1.2] text-foreground">
              Client work first. Then the rest of what we have built along the way.
            </h2>
            <p className="text-sm leading-7 text-muted-foreground sm:text-base">
              The first set is what we are shipping for businesses right now. The second set is other AI work we have built that shows what the team is capable of beyond the agency.
            </p>
          </div>
        }
      />

      <section className="container py-20 sm:py-24">
        <div className="mb-10 max-w-3xl space-y-4">
          <span className="eyebrow">Client work</span>
          <h2 className="text-[clamp(1.8rem,5vw,3.5rem)] font-semibold leading-[1.1] tracking-tight text-foreground">
            Systems we are building for real businesses.
          </h2>
        </div>

        <div className="grid gap-6 lg:grid-cols-3">
          {clientProjects.map((project, index) => (
            <ProjectCard key={project.title} {...project} delay={index * 100} />
          ))}
        </div>
      </section>

      <section className="container py-20 sm:py-24">
        <div className="mb-10 max-w-3xl space-y-4">
          <span className="eyebrow">Other AI work</span>
          <h2 className="text-[clamp(1.8rem,5vw,3.5rem)] font-semibold leading-[1.1] tracking-tight text-foreground">
            Things we have built outside client engagements.
          </h2>
          <p className="text-sm leading-7 text-muted-foreground sm:text-base">
            Independent builds and experiments — useful as proof of what is possible with the same stack.
          </p>
        </div>

        <div className="grid gap-5 lg:grid-cols-3">
          {otherWork.map((item) => (
            <article
              key={item.title}
              className="panel-surface rounded-[1.8rem] p-7 transition-all duration-300 hover:bg-white/[0.06] hover:-translate-y-1"
            >
              <h3 className="text-xl font-semibold tracking-tight leading-[1.2] text-foreground">{item.title}</h3>
              <p className="mt-4 text-sm leading-7 text-muted-foreground">{item.description}</p>
              <div className="mt-5 flex flex-wrap gap-2">
                {item.tags.map((tag) => (
                  <span
                    key={tag}
                    className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-[0.62rem] font-semibold uppercase tracking-[0.18em] text-foreground"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </article>
          ))}
        </div>
      </section>

      <section className="container py-20 sm:py-24">
        <article className="hazard-stripe rounded-[1.8rem] px-6 py-7 shadow-[0_18px_50px_hsl(var(--primary)/0.16)]">
          <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p className="text-[0.68rem] font-semibold uppercase tracking-[0.24em]">Have a workflow in mind?</p>
              <p className="mt-2 text-sm leading-7 text-primary-foreground/80 sm:text-base">
                Tell us how your business runs today. We'll tell you where AI fits — honestly, even if the answer is "not yet".
              </p>
            </div>
            <Button asChild variant="secondary" size="lg">
              <Link to="/contact" className="inline-flex items-center gap-2">
                Start a project
                <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          </div>
        </article>
      </section>
    </SiteLayout>
  );
};

export default Projects;
